qlik-oss/dockerfiles

- .circleci/config.yml
- go-build/Dockerfile
- node-build/Dockerfile
- tiny-build/Dockerfile
> Updating Dockerfiles to fix build, and adding CircleCI

- .circleci/config.yml
- go-build/Dockerfile
- node-build/Dockerfile
- py-build/Dockerfile
- tiny-build/Dockerfile
Pulling the common build Dockerfiles more in-line with each other...
> Harmonizing Dockerfiles

- go-build/Dockerfile
- node-build/Dockerfile
- py-build/Dockerfile
- tiny-build/Dockerfile
> Adding amtool to build images

- node-build/Dockerfile
Moving from `node:8-alpine` to `node:10-alpine`
> Update node-build Dockerfile node version to 10-alpine

- .circleci/config.yml
> Upgrade CircleCI to Docker 18.09.3 and use BuildKit 🐎

- renovate.json
> Change renovate schedule so we don't get rebuilds so often ;)

- go-build/Dockerfile
- node-build/Dockerfile
- py-build/Dockerfile
- tiny-build/Dockerfile
Bump to 19.03!
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
> Upgrade docker to latest

- go-build/Dockerfile
- node-build/Dockerfile
- py-build/Dockerfile
- socat/Dockerfile
- tiny-build/Dockerfile
This'll help renovate keep these images more up-to-date.
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
> Making FROMs more specific

- go-build/Dockerfile
- node-build/Dockerfile
- py-build/Dockerfile
- tiny-build/Dockerfile
Adding as `/usr/local/bin/helm3` so we can use either/or...
> Add helm v3 binary into images

- go-build/Dockerfile
> Update golang base to 1.14.1

- go-build/Dockerfile
> Bump to Go 1.14.2

- tiny-build/Dockerfile
> Add img to tiny-build

- tiny-build/Dockerfile
Adding the latest conftest binary:
https://github.com/open-policy-agent/conftest
> Adding conftest binary

- tiny-build/Dockerfile
> Adding jq package

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
So we don't need to depend on `:latest`...
> Tag images with build date

- docker-kubectl-helm/Dockerfile
- go-build/Dockerfile
- node-build/Dockerfile
- py-build/Dockerfile
- tiny-build/Dockerfile
Ref.: https://hub.docker.com/layers/lachlanevenson/k8s-helm/v3.7.2/images/sha256-4dcc0907150f9f037fe97573ddd006c6d58f5e43fdd6a8e1b8f3effdce1aa9ae?context=explore
> [helm] Use helm 3.7.2

- docker-kubectl-helm/Dockerfile
- go-build/Dockerfile
- node-build/Dockerfile
- py-build/Dockerfile
- tiny-build/Dockerfile
Ref.: https://hub.docker.com/layers/lachlanevenson/k8s-helm/v3.8.0/images/sha256-1e0382b08fee741c31da0f996eb12a3ec2cddaa2c629f9a36c41495007110ba5?context=explore
> feat: bump up helm to v3.8.0

- go-build/Dockerfile
Signed-off-by: Masaru Hoshi <masaru.hoshi@qlik.com>
> [go-build] 1.18.1

- tiny-build/awscli-requirements.txt
The PR will fix this error:
```
urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
```
> Add the Requests to the requirements list

- tiny-build/Dockerfile
Signed-off-by: Masaru Hoshi <masaru.hoshi@qlik.com>
> [tiny-build] Bump up prometheus

- tiny-build/Dockerfile
Adding gh cli to tiny-build images
> feat: adding gh cli to tiny-build images

- node-build/Dockerfile
Signed-off-by: Masaru Hoshi <masaru.hoshi@qlik.com>
> [node-build] alpine 3.21
